/**
 * 상가/사무실 확장 WorkPackageRule — 18~22공종.
 * 가이드: inpick-estimate-v2-product-price-pdf-fix-plan-20260513.md §4-3 (P14-5)
 *
 * 18. 간판·파사드공사
 * 19. 소방공사
 * 20. 환기·후드공사
 * 21. 네트워크·통신공사
 * 22. 냉난방공사
 *
 * 사용 조건: SurfacePlan.projectMode === "commercial" + roomType === "commercial_zone"
 */
import type { WorkPackageRule } from "./types";

/** 18. 간판·파사드 — 3 lines */
export const COMMERCIAL_SIGNAGE_RULE: WorkPackageRule = {
  id: "commercial_signage_facade",
  match: {
    surfaceTypes: ["signage", "facade"],
    materialCategories: ["signage", "facade", "간판", "파사드", "사인"],
    actions: ["new_install", "replace"],
  },
  outputLines: [
    {
      tradeCode: "18",
      tradeNameKo: "간판·파사드공사",
      subTradeCode: "18-01",
      subTradeNameKo: "외부 간판",
      taskNameKo: "외부 간판 제작·설치",
      defaultItemNameKo: "LED 채널사인",
      defaultSpec: "W3000 × H600",
      requiredProductMatch: true,
      highValue: true,
      unit: "set",
      quantityFormula: "manual_one_set",
      costModel: {
        materialUnitPriceKey: "selected_material_unit_price",
        defaultMaterialUnitPrice: 1_800_000,
        defaultLaborUnitPrice: 450_000,
        defaultExpenseUnitPrice: 80_000,
      },
      assumptions: ["LED 채널사인 1식 기준. 광고법 인허가 별도."],
    },
    {
      tradeCode: "18",
      tradeNameKo: "간판·파사드공사",
      subTradeCode: "18-02",
      subTradeNameKo: "파사드 마감",
      taskNameKo: "파사드 외장재 시공",
      defaultItemNameKo: "ACM/세라믹 패널",
      defaultSpec: "두께/규격 협의",
      requiredProductMatch: true,
      highValue: true,
      unit: "m2",
      quantityFormula: "surface_area",
      wasteFactor: 0.05,
      costModel: {
        defaultMaterialUnitPrice: 95_000,
        defaultLaborUnitPrice: 35_000,
        defaultExpenseUnitPrice: 5_000,
      },
      assumptions: ["ACM 패널 기준. 화강석/대리석 변경 시 단가 증가."],
    },
    {
      tradeCode: "18",
      tradeNameKo: "간판·파사드공사",
      subTradeCode: "18-03",
      subTradeNameKo: "내부 안내사인",
      taskNameKo: "내부 안내·픽토그램 사인",
      defaultItemNameKo: "아크릴 사인",
      unit: "ea",
      quantityFormula: "fixture_count",
      quantityMultiplier: 3,
      costModel: {
        defaultMaterialUnitPrice: 85_000,
        defaultLaborUnitPrice: 25_000,
        defaultExpenseUnitPrice: 3_000,
      },
      assumptions: ["입구·화장실·비상구 사인 3ea 기준"],
    },
  ],
};

/** 19. 소방공사 — 4 lines */
export const COMMERCIAL_FIRE_SAFETY_RULE: WorkPackageRule = {
  id: "commercial_fire_safety",
  match: {
    surfaceTypes: ["ceiling", "wall"],
    materialCategories: [
      "fire_safety",
      "sprinkler",
      "smoke_detector",
      "소방",
      "스프링클러",
      "감지기",
    ],
    actions: ["new_install", "replace"],
  },
  outputLines: [
    {
      tradeCode: "19",
      tradeNameKo: "소방공사",
      subTradeCode: "19-01",
      subTradeNameKo: "스프링클러",
      taskNameKo: "스프링클러 헤드 + 배관",
      defaultItemNameKo: "스프링클러 헤드",
      materialCategoryCode: "MEC-FIRE-SPRINKLER",
      requiredProductMatch: true,
      unit: "ea",
      quantityFormula: "manual_one_set",
      quantityMultiplier: 1,
      costModel: {
        defaultMaterialUnitPrice: 35_000,
        defaultLaborUnitPrice: 28_000,
        defaultExpenseUnitPrice: 5_000,
      },
      assumptions: ["10㎡당 1ea 기준. 소방법 따라 추가."],
    },
    {
      tradeCode: "19",
      tradeNameKo: "소방공사",
      subTradeCode: "19-02",
      subTradeNameKo: "감지기",
      taskNameKo: "화재 감지기 설치",
      defaultItemNameKo: "연기/열 감지기",
      materialCategoryCode: "ELE-FIRE-DETECTOR",
      requiredProductMatch: true,
      unit: "ea",
      quantityFormula: "fixture_count",
      quantityMultiplier: 4,
      costModel: {
        defaultMaterialUnitPrice: 28_000,
        defaultLaborUnitPrice: 22_000,
        defaultExpenseUnitPrice: 3_000,
      },
      assumptions: ["조명배치 기준 평균 4ea. 정확한 수량은 소방감리 협의."],
    },
    {
      tradeCode: "19",
      tradeNameKo: "소방공사",
      subTradeCode: "19-03",
      subTradeNameKo: "유도등·비상등",
      taskNameKo: "유도등·비상조명 설치",
      defaultItemNameKo: "LED 유도등",
      unit: "ea",
      quantityFormula: "fixture_count",
      quantityMultiplier: 2,
      costModel: {
        defaultMaterialUnitPrice: 65_000,
        defaultLaborUnitPrice: 25_000,
        defaultExpenseUnitPrice: 3_000,
      },
      assumptions: ["출입구·비상구 2ea 기준"],
    },
    {
      tradeCode: "19",
      tradeNameKo: "소방공사",
      subTradeCode: "19-04",
      subTradeNameKo: "소화기",
      taskNameKo: "소화기 배치",
      defaultItemNameKo: "ABC 분말 소화기 3.3kg",
      unit: "ea",
      quantityFormula: "fixture_count",
      quantityMultiplier: 2,
      costModel: {
        defaultMaterialUnitPrice: 32_000,
        defaultLaborUnitPrice: 8_000,
        defaultExpenseUnitPrice: 1_000,
      },
      assumptions: ["33㎡당 1ea + 표지판 포함"],
    },
  ],
};

/** 20. 환기·후드공사 (상가/사무실 — 가정용과 별도) — 3 lines */
export const COMMERCIAL_VENTILATION_RULE: WorkPackageRule = {
  id: "commercial_ventilation",
  match: {
    surfaceTypes: ["ceiling", "fixture"],
    materialCategories: [
      "commercial_hood",
      "duct",
      "exhaust_fan",
      "환기",
      "덕트",
      "상업용 후드",
    ],
    actions: ["new_install", "replace"],
  },
  outputLines: [
    {
      tradeCode: "20",
      tradeNameKo: "환기·후드공사",
      subTradeCode: "20-01",
      subTradeNameKo: "상업용 후드",
      taskNameKo: "주방 상업용 후드 설치",
      defaultItemNameKo: "스테인리스 후드",
      defaultSpec: "W2000 × H800",
      materialCategoryCode: "MEC-VNT-HOOD",
      requiredProductMatch: true,
      highValue: true,
      unit: "set",
      quantityFormula: "manual_one_set",
      costModel: {
        materialUnitPriceKey: "selected_material_unit_price",
        defaultMaterialUnitPrice: 1_500_000,
        defaultLaborUnitPrice: 380_000,
        defaultExpenseUnitPrice: 80_000,
      },
      assumptions: ["상업용 (식당/카페) 후드. 가정용은 14 주방공사 참조."],
    },
    {
      tradeCode: "20",
      tradeNameKo: "환기·후드공사",
      subTradeCode: "20-02",
      subTradeNameKo: "덕트 배관",
      taskNameKo: "스파이럴 덕트 배관",
      defaultItemNameKo: "갈바늄 스파이럴 덕트",
      defaultSpec: "Ø200",
      materialCategoryCode: "MEC-VNT-FAN",
      unit: "m",
      quantityFormula: "manual_one_set",
      quantityMultiplier: 6,
      costModel: {
        defaultMaterialUnitPrice: 42_000,
        defaultLaborUnitPrice: 35_000,
        defaultExpenseUnitPrice: 4_000,
      },
      assumptions: ["6m 평균. 옥상까지 직선 거리 기준."],
    },
    {
      tradeCode: "20",
      tradeNameKo: "환기·후드공사",
      subTradeCode: "20-03",
      subTradeNameKo: "환기 시스템",
      taskNameKo: "환기팬 + 댐퍼",
      defaultItemNameKo: "환기팬 + 역류방지 댐퍼",
      materialCategoryCode: "MEC-VNT-FAN",
      requiredProductMatch: true,
      unit: "set",
      quantityFormula: "manual_one_set",
      costModel: {
        defaultMaterialUnitPrice: 280_000,
        defaultLaborUnitPrice: 120_000,
        defaultExpenseUnitPrice: 15_000,
      },
      assumptions: ["환기풍량 협의. 식당 600cmh 기준."],
    },
  ],
};

/** 21. 네트워크·통신공사 — 4 lines */
export const COMMERCIAL_NETWORK_RULE: WorkPackageRule = {
  id: "commercial_network",
  match: {
    surfaceTypes: ["wall", "ceiling", "lighting"],
    materialCategories: [
      "network",
      "lan",
      "wifi",
      "utp",
      "cctv",
      "통신",
      "네트워크",
      "랜선",
    ],
    actions: ["new_install"],
  },
  outputLines: [
    {
      tradeCode: "21",
      tradeNameKo: "네트워크·통신공사",
      subTradeCode: "21-01",
      subTradeNameKo: "UTP 포설",
      taskNameKo: "UTP Cat.6 케이블 포설",
      defaultItemNameKo: "UTP Cat.6 케이블",
      defaultSpec: "Cat.6 단심",
      materialCategoryCode: "ELE-COM-UTP",
      requiredProductMatch: true,
      unit: "m",
      quantityFormula: "manual_one_set",
      quantityMultiplier: 50,
      costModel: {
        defaultMaterialUnitPrice: 1_500,
        defaultLaborUnitPrice: 3_500,
        defaultExpenseUnitPrice: 200,
      },
      assumptions: ["평균 50m. 통신함→AP+LAN 단자 분기."],
    },
    {
      tradeCode: "21",
      tradeNameKo: "네트워크·통신공사",
      subTradeCode: "21-02",
      subTradeNameKo: "LAN 단자",
      taskNameKo: "벽 LAN 단자 설치",
      defaultItemNameKo: "Cat.6 LAN 단자",
      materialCategoryCode: "ELE-OUT-LAN",
      requiredProductMatch: true,
      unit: "ea",
      quantityFormula: "fixture_count",
      quantityMultiplier: 4,
      costModel: {
        defaultMaterialUnitPrice: 18_000,
        defaultLaborUnitPrice: 15_000,
        defaultExpenseUnitPrice: 2_000,
      },
      assumptions: ["좌석/카운터/사무실 평균 4ea"],
    },
    {
      tradeCode: "21",
      tradeNameKo: "네트워크·통신공사",
      subTradeCode: "21-03",
      subTradeNameKo: "무선 AP",
      taskNameKo: "무선 AP 설치",
      defaultItemNameKo: "Wi-Fi 6 AP",
      unit: "ea",
      quantityFormula: "fixture_count",
      quantityMultiplier: 1,
      costModel: {
        defaultMaterialUnitPrice: 220_000,
        defaultLaborUnitPrice: 35_000,
        defaultExpenseUnitPrice: 5_000,
      },
      assumptions: ["1개 평균. 면적 50평+은 2ea 권장."],
    },
    {
      tradeCode: "21",
      tradeNameKo: "네트워크·통신공사",
      subTradeCode: "21-04",
      subTradeNameKo: "CCTV",
      taskNameKo: "CCTV 카메라 + NVR",
      defaultItemNameKo: "200만화소 IP 카메라 + NVR",
      unit: "set",
      quantityFormula: "manual_one_set",
      costModel: {
        materialUnitPriceKey: "selected_material_unit_price",
        defaultMaterialUnitPrice: 850_000,
        defaultLaborUnitPrice: 180_000,
        defaultExpenseUnitPrice: 25_000,
      },
      assumptions: ["카메라 4ch + NVR 1식. 추가 채널은 별도."],
    },
  ],
};

/** 22. 냉난방공사 (시스템에어컨 등) — 3 lines */
export const COMMERCIAL_HVAC_RULE: WorkPackageRule = {
  id: "commercial_hvac",
  match: {
    surfaceTypes: ["ceiling", "fixture"],
    materialCategories: [
      "hvac",
      "system_ac",
      "air_conditioner",
      "냉난방",
      "에어컨",
      "시스템에어컨",
    ],
    actions: ["new_install", "replace"],
  },
  outputLines: [
    {
      tradeCode: "22",
      tradeNameKo: "냉난방공사",
      subTradeCode: "22-01",
      subTradeNameKo: "시스템에어컨 실내기",
      taskNameKo: "시스템에어컨 실내기 설치",
      defaultItemNameKo: "천장형 4way 카세트",
      defaultSpec: "10평형",
      materialCategoryCode: "MEC-HVAC-AC",
      requiredProductMatch: true,
      highValue: true,
      unit: "ea",
      quantityFormula: "fixture_count",
      quantityMultiplier: 2,
      costModel: {
        materialUnitPriceKey: "selected_material_unit_price",
        defaultMaterialUnitPrice: 1_650_000,
        defaultLaborUnitPrice: 280_000,
        defaultExpenseUnitPrice: 35_000,
      },
      assumptions: ["10평형 실내기 2ea. 면적별 조정 필요."],
    },
    {
      tradeCode: "22",
      tradeNameKo: "냉난방공사",
      subTradeCode: "22-02",
      subTradeNameKo: "실외기",
      taskNameKo: "실외기 설치",
      defaultItemNameKo: "시스템 실외기",
      materialCategoryCode: "MEC-HVAC-AC",
      requiredProductMatch: true,
      highValue: true,
      unit: "ea",
      quantityFormula: "fixture_count",
      quantityMultiplier: 1,
      costModel: {
        materialUnitPriceKey: "selected_material_unit_price",
        defaultMaterialUnitPrice: 2_800_000,
        defaultLaborUnitPrice: 380_000,
        defaultExpenseUnitPrice: 50_000,
      },
      assumptions: ["20평형 실외기 1ea. 옥상/베란다 거치 별도."],
    },
    {
      tradeCode: "22",
      tradeNameKo: "냉난방공사",
      subTradeCode: "22-03",
      subTradeNameKo: "냉매 배관",
      taskNameKo: "냉매 배관 + 드레인",
      defaultItemNameKo: "동관 + 보온 + 드레인",
      unit: "m",
      quantityFormula: "manual_one_set",
      quantityMultiplier: 15,
      costModel: {
        defaultMaterialUnitPrice: 28_000,
        defaultLaborUnitPrice: 22_000,
        defaultExpenseUnitPrice: 3_000,
      },
      assumptions: ["실내기 2ea 평균 15m"],
    },
  ],
};

export const ALL_COMMERCIAL_RULES: WorkPackageRule[] = [
  COMMERCIAL_SIGNAGE_RULE,
  COMMERCIAL_FIRE_SAFETY_RULE,
  COMMERCIAL_VENTILATION_RULE,
  COMMERCIAL_NETWORK_RULE,
  COMMERCIAL_HVAC_RULE,
];
