/**
 * WorkPackageRule — SurfacePlan을 실제 공사 작업 라인으로 전개하는 규칙.
 * 가이드: inpick-construction-trade-estimate-engine-dev-plan-20260512.md §6
 *
 * 입력 자재 1개 → 5~7개 라인으로 자동 전개 (철거→바탕→부자재→마감→폐기물).
 * 단가는 단가/노무비/경비 분리 + 손실률 적용.
 */
import type { WorkPackageRule } from "./types";

/** 1. 강마루/원목마루/마루류 — 6 lines */
export const WOOD_FLOOR_RULE: WorkPackageRule = {
  id: "floor_wood_flooring_demolish_and_new",
  match: {
    surfaceTypes: ["floor"],
    materialCategories: [
      "wood_floor",
      "engineered_floor",
      "engineered_wood",
      "solid_wood",
      "강마루",
      "원목마루",
      "마루",
    ],
    actions: ["replace", "demolish_and_new", "new_install"],
  },
  outputLines: [
    {
      tradeCode: "02",
      tradeNameKo: "철거공사",
      subTradeCode: "02-01",
      subTradeNameKo: "기존마감 철거",
      taskNameKo: "기존 바닥재 철거",
      defaultItemNameKo: "기존 마루/장판 철거",
      unit: "m2",
      quantityFormula: "floor_area",
      costModel: { defaultLaborUnitPrice: 12000, defaultExpenseUnitPrice: 1200 },
      assumptions: ["기존 바닥재 철거가 필요한 것으로 가정했습니다."],
    },
    {
      tradeCode: "10",
      tradeNameKo: "바닥재공사",
      subTradeCode: "10-01",
      subTradeNameKo: "바탕처리",
      taskNameKo: "바탕면 정리 및 평활 보수",
      defaultItemNameKo: "바탕면 정리",
      unit: "m2",
      quantityFormula: "floor_area",
      costModel: {
        defaultMaterialUnitPrice: 3000,
        defaultLaborUnitPrice: 6000,
        defaultExpenseUnitPrice: 500,
      },
      assumptions: ["바닥 평활 상태는 현장 실측 후 조정될 수 있습니다."],
    },
    {
      tradeCode: "10",
      tradeNameKo: "바닥재공사",
      subTradeCode: "10-02",
      subTradeNameKo: "부자재",
      taskNameKo: "방습지·접착제·부자재",
      defaultItemNameKo: "마루 부자재",
      unit: "m2",
      quantityFormula: "floor_area",
      wasteFactor: 0.05,
      costModel: {
        defaultMaterialUnitPrice: 5500,
        defaultLaborUnitPrice: 0,
        defaultExpenseUnitPrice: 300,
      },
      assumptions: ["자재 손실률 5%를 적용했습니다."],
    },
    {
      tradeCode: "10",
      tradeNameKo: "바닥재공사",
      subTradeCode: "10-03",
      subTradeNameKo: "마감 시공",
      taskNameKo: "강마루 시공",
      defaultItemNameKo: "강마루",
      defaultSpec: "7.5T",
      unit: "m2",
      quantityFormula: "floor_area",
      wasteFactor: 0.05,
      costModel: {
        materialUnitPriceKey: "selected_material_unit_price",
        defaultMaterialUnitPrice: 65000,
        defaultLaborUnitPrice: 18000,
        defaultExpenseUnitPrice: 2500,
      },
      assumptions: ["선택 자재 단가가 없으면 표준 강마루 단가를 적용합니다."],
    },
    {
      tradeCode: "10",
      tradeNameKo: "바닥재공사",
      subTradeCode: "10-04",
      subTradeNameKo: "걸레받이",
      taskNameKo: "걸레받이 시공",
      defaultItemNameKo: "MDF/PVC 걸레받이",
      defaultSpec: "80mm",
      unit: "m",
      quantityFormula: "room_perimeter",
      wasteFactor: 0.05,
      costModel: {
        defaultMaterialUnitPrice: 4500,
        defaultLaborUnitPrice: 6000,
        defaultExpenseUnitPrice: 500,
      },
      assumptions: ["문 개구부 차감은 정밀 도면 확보 시 반영합니다."],
    },
    {
      tradeCode: "15",
      tradeNameKo: "폐기물·운반·양중",
      subTradeCode: "15-01",
      subTradeNameKo: "폐기물 반출",
      taskNameKo: "바닥재 폐기물 반출",
      defaultItemNameKo: "폐기물 반출",
      unit: "lot",
      quantityFormula: "waste_volume_estimate",
      costModel: {
        defaultMaterialUnitPrice: 0,
        defaultLaborUnitPrice: 40000,
        defaultExpenseUnitPrice: 60000,
      },
      assumptions: ["폐기물량은 면적 기준으로 추정했습니다."],
    },
  ],
};

/** 2. 실크벽지/도배 — 4 lines */
export const WALLPAPER_RULE: WorkPackageRule = {
  id: "wall_wallpaper_replace",
  match: {
    surfaceTypes: ["wall", "ceiling"],
    materialCategories: [
      "wallpaper",
      "silk_wallpaper",
      "paper_wallpaper",
      "합지",
      "실크벽지",
      "도배",
      "벽지",
    ],
    actions: ["replace", "demolish_and_new", "new_install"],
  },
  outputLines: [
    {
      tradeCode: "02",
      tradeNameKo: "철거공사",
      subTradeCode: "02-02",
      subTradeNameKo: "기존벽지 제거",
      taskNameKo: "기존 벽지 제거",
      defaultItemNameKo: "기존 벽지 제거",
      unit: "m2",
      quantityFormula: "surface_area",
      costModel: { defaultLaborUnitPrice: 2500, defaultExpenseUnitPrice: 300 },
      assumptions: ["기존 벽지 제거가 필요한 것으로 가정했습니다."],
    },
    {
      tradeCode: "09",
      tradeNameKo: "도배공사",
      subTradeCode: "09-01",
      subTradeNameKo: "바탕처리",
      taskNameKo: "바탕면 보수",
      defaultItemNameKo: "퍼티·면정리",
      unit: "m2",
      quantityFormula: "surface_area",
      costModel: {
        defaultMaterialUnitPrice: 1200,
        defaultLaborUnitPrice: 2500,
        defaultExpenseUnitPrice: 200,
      },
      assumptions: ["벽면 크랙·못자국 보수는 기본 보수 범위로 산정했습니다."],
    },
    {
      tradeCode: "09",
      tradeNameKo: "도배공사",
      subTradeCode: "09-02",
      subTradeNameKo: "초배",
      taskNameKo: "초배지 시공",
      defaultItemNameKo: "초배지",
      unit: "m2",
      quantityFormula: "surface_area",
      wasteFactor: 0.05,
      costModel: {
        defaultMaterialUnitPrice: 1800,
        defaultLaborUnitPrice: 2200,
        defaultExpenseUnitPrice: 150,
      },
      assumptions: ["도배지 손실률 5%를 적용했습니다."],
    },
    {
      tradeCode: "09",
      tradeNameKo: "도배공사",
      subTradeCode: "09-03",
      subTradeNameKo: "마감 도배",
      taskNameKo: "실크벽지 시공",
      defaultItemNameKo: "실크벽지",
      unit: "m2",
      quantityFormula: "surface_area",
      wasteFactor: 0.05,
      costModel: {
        materialUnitPriceKey: "selected_material_unit_price",
        defaultMaterialUnitPrice: 8500,
        defaultLaborUnitPrice: 7000,
        defaultExpenseUnitPrice: 500,
      },
      assumptions: ["선택 벽지 단가가 없으면 표준 실크벽지 단가를 적용합니다."],
    },
  ],
};

/** 3. 포세린 타일 — 4 lines + 습식공간 방수 */
export const PORCELAIN_TILE_RULE: WorkPackageRule = {
  id: "tile_porcelain_demolish_and_new",
  match: {
    surfaceTypes: ["floor", "wall"],
    materialCategories: [
      "porcelain_tile",
      "tile",
      "wall_tile",
      "포세린타일",
      "타일",
      "벽타일",
    ],
    actions: ["replace", "demolish_and_new", "new_install"],
  },
  outputLines: [
    {
      tradeCode: "02",
      tradeNameKo: "철거공사",
      subTradeCode: "02-03",
      subTradeNameKo: "기존 타일 철거",
      taskNameKo: "기존 타일 철거",
      defaultItemNameKo: "기존 타일 철거",
      unit: "m2",
      quantityFormula: "surface_area",
      costModel: { defaultLaborUnitPrice: 18000, defaultExpenseUnitPrice: 2500 },
      assumptions: ["기존 타일 철거가 필요한 경우로 산정했습니다."],
    },
    {
      tradeCode: "06",
      tradeNameKo: "방수공사",
      subTradeCode: "06-01",
      subTradeNameKo: "바닥·벽체 방수",
      taskNameKo: "방수 시공",
      defaultItemNameKo: "액체방수/도막방수",
      unit: "m2",
      quantityFormula: "surface_area",
      costModel: {
        defaultMaterialUnitPrice: 9000,
        defaultLaborUnitPrice: 12000,
        defaultExpenseUnitPrice: 1000,
      },
      includeWhen: {
        roomTypes: ["bathroom", "kitchen", "balcony", "utility"],
      },
      assumptions: ["욕실·주방·발코니 등 습식공간에 방수를 적용합니다."],
    },
    {
      tradeCode: "07",
      tradeNameKo: "타일공사",
      subTradeCode: "07-01",
      subTradeNameKo: "타일 시공",
      taskNameKo: "포세린 타일 시공",
      defaultItemNameKo: "포세린 타일",
      defaultSpec: "600×600",
      unit: "m2",
      quantityFormula: "surface_area",
      wasteFactor: 0.07,
      costModel: {
        materialUnitPriceKey: "selected_material_unit_price",
        defaultMaterialUnitPrice: 38000,
        defaultLaborUnitPrice: 35000,
        defaultExpenseUnitPrice: 3000,
      },
      assumptions: ["타일 손실률 7%를 적용했습니다."],
    },
    {
      tradeCode: "07",
      tradeNameKo: "타일공사",
      subTradeCode: "07-02",
      subTradeNameKo: "줄눈",
      taskNameKo: "줄눈 시공",
      defaultItemNameKo: "줄눈재",
      unit: "m2",
      quantityFormula: "surface_area",
      costModel: {
        defaultMaterialUnitPrice: 2500,
        defaultLaborUnitPrice: 4000,
        defaultExpenseUnitPrice: 300,
      },
      assumptions: ["일반 줄눈 기준입니다."],
    },
  ],
};

/** 4. 욕실 전체 리모델링 패키지 — 6 lines */
export const BATHROOM_FULL_REMODEL_RULE: WorkPackageRule = {
  id: "bathroom_full_remodel_standard",
  match: {
    roomTypes: ["bathroom"],
    surfaceTypes: ["floor", "wall", "ceiling", "fixture"],
    materialCategories: ["bathroom_full", "bathroom", "욕실전체", "욕실"],
    actions: ["demolish_and_new", "replace"],
  },
  outputLines: [
    {
      tradeCode: "02",
      tradeNameKo: "철거공사",
      subTradeCode: "02-10",
      subTradeNameKo: "욕실 철거",
      taskNameKo: "욕실 기존 마감 및 도기 철거",
      defaultItemNameKo: "욕실 철거",
      unit: "set",
      quantityFormula: "manual_one_set",
      costModel: { defaultLaborUnitPrice: 350000, defaultExpenseUnitPrice: 120000 },
      assumptions: ["욕실 1칸 기준 철거입니다."],
    },
    {
      tradeCode: "05",
      tradeNameKo: "설비공사",
      subTradeCode: "05-10",
      subTradeNameKo: "욕실 배관",
      taskNameKo: "급수·배수 배관 보수",
      defaultItemNameKo: "욕실 배관 보수",
      unit: "set",
      quantityFormula: "manual_one_set",
      costModel: {
        defaultMaterialUnitPrice: 180000,
        defaultLaborUnitPrice: 280000,
        defaultExpenseUnitPrice: 40000,
      },
      assumptions: ["배관 전체 교체가 아닌 기본 위치 보수 기준입니다."],
    },
    {
      tradeCode: "06",
      tradeNameKo: "방수공사",
      subTradeCode: "06-10",
      subTradeNameKo: "욕실 방수",
      taskNameKo: "욕실 바닥·벽체 하부 방수",
      defaultItemNameKo: "욕실 방수",
      unit: "set",
      quantityFormula: "manual_one_set",
      costModel: {
        defaultMaterialUnitPrice: 90000,
        defaultLaborUnitPrice: 180000,
        defaultExpenseUnitPrice: 20000,
      },
      assumptions: ["담수 테스트 포함 여부는 현장 정책에 따라 조정합니다."],
    },
    {
      tradeCode: "07",
      tradeNameKo: "타일공사",
      subTradeCode: "07-10",
      subTradeNameKo: "욕실 타일",
      taskNameKo: "욕실 바닥·벽 타일 시공",
      defaultItemNameKo: "욕실 타일",
      unit: "set",
      quantityFormula: "manual_one_set",
      costModel: {
        defaultMaterialUnitPrice: 650000,
        defaultLaborUnitPrice: 850000,
        defaultExpenseUnitPrice: 80000,
      },
      assumptions: ["욕실 표준 면적 기준 타일 패키지입니다."],
    },
    {
      tradeCode: "13",
      tradeNameKo: "욕실공사",
      subTradeCode: "13-01",
      subTradeNameKo: "도기·수전",
      taskNameKo: "양변기·세면기·수전 설치",
      defaultItemNameKo: "욕실 도기·수전",
      unit: "set",
      quantityFormula: "manual_one_set",
      costModel: {
        defaultMaterialUnitPrice: 780000,
        defaultLaborUnitPrice: 280000,
        defaultExpenseUnitPrice: 30000,
      },
      assumptions: ["표준형 도기와 수전 기준입니다."],
    },
    {
      tradeCode: "13",
      tradeNameKo: "욕실공사",
      subTradeCode: "13-02",
      subTradeNameKo: "천장·환풍기",
      taskNameKo: "욕실 천장재 및 환풍기 설치",
      defaultItemNameKo: "SMC 천장·환풍기",
      unit: "set",
      quantityFormula: "manual_one_set",
      costModel: {
        defaultMaterialUnitPrice: 180000,
        defaultLaborUnitPrice: 220000,
        defaultExpenseUnitPrice: 20000,
      },
      assumptions: ["돔천장 또는 SMC 천장 기본 기준입니다."],
    },
  ],
};

/** 5. 주방 패키지 — 5 lines */
export const KITCHEN_STANDARD_RULE: WorkPackageRule = {
  id: "kitchen_standard_remodel",
  match: {
    roomTypes: ["kitchen"],
    surfaceTypes: ["counter", "cabinet", "sink", "wall", "lighting"],
    materialCategories: [
      "kitchen_standard",
      "kitchen_cabinet",
      "sink_cabinet",
      "주방",
      "싱크대",
    ],
    actions: ["replace", "demolish_and_new", "new_install"],
  },
  outputLines: [
    {
      tradeCode: "02",
      tradeNameKo: "철거공사",
      subTradeCode: "02-20",
      subTradeNameKo: "주방 철거",
      taskNameKo: "기존 싱크대 및 주방 가구 철거",
      defaultItemNameKo: "싱크대 철거",
      unit: "set",
      quantityFormula: "manual_one_set",
      costModel: { defaultLaborUnitPrice: 180000, defaultExpenseUnitPrice: 60000 },
      assumptions: [],
    },
    {
      tradeCode: "05",
      tradeNameKo: "설비공사",
      subTradeCode: "05-20",
      subTradeNameKo: "주방 급배수",
      taskNameKo: "주방 급배수 연결",
      defaultItemNameKo: "급배수 연결",
      unit: "set",
      quantityFormula: "manual_one_set",
      costModel: {
        defaultMaterialUnitPrice: 80000,
        defaultLaborUnitPrice: 160000,
        defaultExpenseUnitPrice: 20000,
      },
      assumptions: [],
    },
    {
      tradeCode: "04",
      tradeNameKo: "전기공사",
      subTradeCode: "04-20",
      subTradeNameKo: "주방 전기",
      taskNameKo: "주방 콘센트·조명 배선",
      defaultItemNameKo: "주방 전기 배선",
      unit: "set",
      quantityFormula: "manual_one_set",
      costModel: {
        defaultMaterialUnitPrice: 120000,
        defaultLaborUnitPrice: 220000,
        defaultExpenseUnitPrice: 30000,
      },
      assumptions: [],
    },
    {
      tradeCode: "12",
      tradeNameKo: "가구·싱크공사",
      subTradeCode: "12-10",
      subTradeNameKo: "싱크대",
      taskNameKo: "싱크대 하부장·상부장 설치",
      defaultItemNameKo: "싱크대",
      unit: "set",
      quantityFormula: "manual_one_set",
      costModel: {
        materialUnitPriceKey: "selected_material_unit_price",
        defaultMaterialUnitPrice: 1800000,
        defaultLaborUnitPrice: 450000,
        defaultExpenseUnitPrice: 80000,
      },
      assumptions: ["기본형 싱크대 기준입니다."],
    },
    {
      tradeCode: "14",
      tradeNameKo: "주방공사",
      subTradeCode: "14-01",
      subTradeNameKo: "상판·벽마감",
      taskNameKo: "주방 상판 및 벽면 마감",
      defaultItemNameKo: "주방 상판·벽마감",
      unit: "set",
      quantityFormula: "manual_one_set",
      costModel: {
        defaultMaterialUnitPrice: 650000,
        defaultLaborUnitPrice: 220000,
        defaultExpenseUnitPrice: 30000,
      },
      assumptions: [],
    },
  ],
};

/** 모든 규칙 — 견적 엔진이 surfacePlan과 매칭할 때 순회 */
export const ALL_WORK_PACKAGE_RULES: WorkPackageRule[] = [
  WOOD_FLOOR_RULE,
  WALLPAPER_RULE,
  PORCELAIN_TILE_RULE,
  BATHROOM_FULL_REMODEL_RULE,
  KITCHEN_STANDARD_RULE,
];
