/**
 * WorkPackageRule — SurfacePlan을 실제 공사 작업 라인으로 전개하는 규칙.
 * 가이드: inpick-construction-trade-estimate-engine-dev-plan-20260512.md §6
 *
 * 입력 자재 1개 → 5~7개 라인으로 자동 전개 (철거→바탕→부자재→마감→폐기물).
 * 단가는 단가/노무비/경비 분리 + 손실률 적용.
 */
import type { WorkPackageRule } from "./types";

/** 1. 강마루/원목마루/마루류 — 6 lines */
export const WOOD_FLOOR_RULE: WorkPackageRule = {
  id: "floor_wood_flooring_demolish_and_new",
  match: {
    surfaceTypes: ["floor"],
    materialCategories: [
      "wood_floor",
      "engineered_floor",
      "engineered_wood",
      "solid_wood",
      "강마루",
      "원목마루",
      "마루",
    ],
    actions: ["replace", "demolish_and_new", "new_install"],
  },
  outputLines: [
    {
      tradeCode: "02",
      tradeNameKo: "철거공사",
      subTradeCode: "02-01",
      subTradeNameKo: "기존마감 철거",
      taskNameKo: "기존 바닥재 철거",
      defaultItemNameKo: "기존 마루/장판 철거",
      unit: "m2",
      quantityFormula: "floor_area",
      costModel: { defaultLaborUnitPrice: 12000, defaultExpenseUnitPrice: 1200 },
      assumptions: ["기존 바닥재 철거가 필요한 것으로 가정했습니다."],
    },
    {
      tradeCode: "10",
      tradeNameKo: "바닥재공사",
      subTradeCode: "10-01",
      subTradeNameKo: "바탕처리",
      taskNameKo: "바탕면 정리 및 평활 보수",
      defaultItemNameKo: "바탕면 정리",
      unit: "m2",
      quantityFormula: "floor_area",
      costModel: {
        defaultMaterialUnitPrice: 3000,
        defaultLaborUnitPrice: 6000,
        defaultExpenseUnitPrice: 500,
      },
      assumptions: ["바닥 평활 상태는 현장 실측 후 조정될 수 있습니다."],
    },
    {
      tradeCode: "10",
      tradeNameKo: "바닥재공사",
      subTradeCode: "10-02",
      subTradeNameKo: "부자재",
      taskNameKo: "방습지·접착제·부자재",
      defaultItemNameKo: "마루 부자재",
      unit: "m2",
      quantityFormula: "floor_area",
      wasteFactor: 0.05,
      costModel: {
        defaultMaterialUnitPrice: 5500,
        defaultLaborUnitPrice: 0,
        defaultExpenseUnitPrice: 300,
      },
      assumptions: ["자재 손실률 5%를 적용했습니다."],
    },
    {
      tradeCode: "10",
      tradeNameKo: "바닥재공사",
      subTradeCode: "10-03",
      subTradeNameKo: "마감 시공",
      taskNameKo: "강마루 시공",
      defaultItemNameKo: "강마루",
      defaultSpec: "7.5T",
      unit: "m2",
      quantityFormula: "floor_area",
      wasteFactor: 0.05,
      costModel: {
        materialUnitPriceKey: "selected_material_unit_price",
        defaultMaterialUnitPrice: 65000,
        defaultLaborUnitPrice: 18000,
        defaultExpenseUnitPrice: 2500,
      },
      assumptions: ["선택 자재 단가가 없으면 표준 강마루 단가를 적용합니다."],
    },
    {
      tradeCode: "10",
      tradeNameKo: "바닥재공사",
      subTradeCode: "10-04",
      subTradeNameKo: "걸레받이",
      taskNameKo: "걸레받이 시공",
      defaultItemNameKo: "MDF/PVC 걸레받이",
      defaultSpec: "80mm",
      unit: "m",
      quantityFormula: "room_perimeter",
      wasteFactor: 0.05,
      costModel: {
        defaultMaterialUnitPrice: 4500,
        defaultLaborUnitPrice: 6000,
        defaultExpenseUnitPrice: 500,
      },
      assumptions: ["문 개구부 차감은 정밀 도면 확보 시 반영합니다."],
    },
    {
      tradeCode: "15",
      tradeNameKo: "폐기물·운반·양중",
      subTradeCode: "15-01",
      subTradeNameKo: "폐기물 반출",
      taskNameKo: "바닥재 폐기물 반출",
      defaultItemNameKo: "폐기물 반출",
      unit: "lot",
      quantityFormula: "waste_volume_estimate",
      costModel: {
        defaultMaterialUnitPrice: 0,
        defaultLaborUnitPrice: 40000,
        defaultExpenseUnitPrice: 60000,
      },
      assumptions: ["폐기물량은 면적 기준으로 추정했습니다."],
    },
  ],
};

/** 2. 실크벽지/도배 — 4 lines */
export const WALLPAPER_RULE: WorkPackageRule = {
  id: "wall_wallpaper_replace",
  match: {
    surfaceTypes: ["wall", "ceiling"],
    materialCategories: [
      "wallpaper",
      "silk_wallpaper",
      "paper_wallpaper",
      "합지",
      "실크벽지",
      "도배",
      "벽지",
    ],
    actions: ["replace", "demolish_and_new", "new_install"],
  },
  outputLines: [
    {
      tradeCode: "02",
      tradeNameKo: "철거공사",
      subTradeCode: "02-02",
      subTradeNameKo: "기존벽지 제거",
      taskNameKo: "기존 벽지 제거",
      defaultItemNameKo: "기존 벽지 제거",
      unit: "m2",
      quantityFormula: "surface_area",
      costModel: { defaultLaborUnitPrice: 2500, defaultExpenseUnitPrice: 300 },
      assumptions: ["기존 벽지 제거가 필요한 것으로 가정했습니다."],
    },
    {
      tradeCode: "09",
      tradeNameKo: "도배공사",
      subTradeCode: "09-01",
      subTradeNameKo: "바탕처리",
      taskNameKo: "바탕면 보수",
      defaultItemNameKo: "퍼티·면정리",
      unit: "m2",
      quantityFormula: "surface_area",
      costModel: {
        defaultMaterialUnitPrice: 1200,
        defaultLaborUnitPrice: 2500,
        defaultExpenseUnitPrice: 200,
      },
      assumptions: ["벽면 크랙·못자국 보수는 기본 보수 범위로 산정했습니다."],
    },
    {
      tradeCode: "09",
      tradeNameKo: "도배공사",
      subTradeCode: "09-02",
      subTradeNameKo: "초배",
      taskNameKo: "초배지 시공",
      defaultItemNameKo: "초배지",
      unit: "m2",
      quantityFormula: "surface_area",
      wasteFactor: 0.05,
      costModel: {
        defaultMaterialUnitPrice: 1800,
        defaultLaborUnitPrice: 2200,
        defaultExpenseUnitPrice: 150,
      },
      assumptions: ["도배지 손실률 5%를 적용했습니다."],
    },
    {
      tradeCode: "09",
      tradeNameKo: "도배공사",
      subTradeCode: "09-03",
      subTradeNameKo: "마감 도배",
      taskNameKo: "실크벽지 시공",
      defaultItemNameKo: "실크벽지",
      unit: "m2",
      quantityFormula: "surface_area",
      wasteFactor: 0.05,
      costModel: {
        materialUnitPriceKey: "selected_material_unit_price",
        defaultMaterialUnitPrice: 8500,
        defaultLaborUnitPrice: 7000,
        defaultExpenseUnitPrice: 500,
      },
      assumptions: ["선택 벽지 단가가 없으면 표준 실크벽지 단가를 적용합니다."],
    },
  ],
};

/** 3. 포세린 타일 — 4 lines + 습식공간 방수 */
export const PORCELAIN_TILE_RULE: WorkPackageRule = {
  id: "tile_porcelain_demolish_and_new",
  match: {
    surfaceTypes: ["floor", "wall"],
    materialCategories: [
      "porcelain_tile",
      "tile",
      "wall_tile",
      "포세린타일",
      "타일",
      "벽타일",
    ],
    actions: ["replace", "demolish_and_new", "new_install"],
  },
  outputLines: [
    {
      tradeCode: "02",
      tradeNameKo: "철거공사",
      subTradeCode: "02-03",
      subTradeNameKo: "기존 타일 철거",
      taskNameKo: "기존 타일 철거",
      defaultItemNameKo: "기존 타일 철거",
      unit: "m2",
      quantityFormula: "surface_area",
      costModel: { defaultLaborUnitPrice: 18000, defaultExpenseUnitPrice: 2500 },
      assumptions: ["기존 타일 철거가 필요한 경우로 산정했습니다."],
    },
    {
      tradeCode: "06",
      tradeNameKo: "방수공사",
      subTradeCode: "06-01",
      subTradeNameKo: "바닥·벽체 방수",
      taskNameKo: "방수 시공",
      defaultItemNameKo: "액체방수/도막방수",
      unit: "m2",
      quantityFormula: "surface_area",
      costModel: {
        defaultMaterialUnitPrice: 9000,
        defaultLaborUnitPrice: 12000,
        defaultExpenseUnitPrice: 1000,
      },
      includeWhen: {
        roomTypes: ["bathroom", "kitchen", "balcony", "utility"],
      },
      assumptions: ["욕실·주방·발코니 등 습식공간에 방수를 적용합니다."],
    },
    {
      tradeCode: "07",
      tradeNameKo: "타일공사",
      subTradeCode: "07-01",
      subTradeNameKo: "타일 시공",
      taskNameKo: "포세린 타일 시공",
      defaultItemNameKo: "포세린 타일",
      defaultSpec: "600×600",
      unit: "m2",
      quantityFormula: "surface_area",
      wasteFactor: 0.07,
      costModel: {
        materialUnitPriceKey: "selected_material_unit_price",
        defaultMaterialUnitPrice: 38000,
        defaultLaborUnitPrice: 35000,
        defaultExpenseUnitPrice: 3000,
      },
      assumptions: ["타일 손실률 7%를 적용했습니다."],
    },
    {
      tradeCode: "07",
      tradeNameKo: "타일공사",
      subTradeCode: "07-02",
      subTradeNameKo: "줄눈",
      taskNameKo: "줄눈 시공",
      defaultItemNameKo: "줄눈재",
      unit: "m2",
      quantityFormula: "surface_area",
      costModel: {
        defaultMaterialUnitPrice: 2500,
        defaultLaborUnitPrice: 4000,
        defaultExpenseUnitPrice: 300,
      },
      assumptions: ["일반 줄눈 기준입니다."],
    },
  ],
};

/** 4. 욕실 전체 리모델링 패키지 — 6 lines */
export const BATHROOM_FULL_REMODEL_RULE: WorkPackageRule = {
  id: "bathroom_full_remodel_standard",
  match: {
    roomTypes: ["bathroom"],
    surfaceTypes: ["floor", "wall", "ceiling", "fixture"],
    materialCategories: ["bathroom_full", "bathroom", "욕실전체", "욕실"],
    actions: ["demolish_and_new", "replace"],
  },
  outputLines: [
    {
      tradeCode: "02",
      tradeNameKo: "철거공사",
      subTradeCode: "02-10",
      subTradeNameKo: "욕실 철거",
      taskNameKo: "욕실 기존 마감 및 도기 철거",
      defaultItemNameKo: "욕실 철거",
      unit: "set",
      quantityFormula: "manual_one_set",
      costModel: { defaultLaborUnitPrice: 350000, defaultExpenseUnitPrice: 120000 },
      assumptions: ["욕실 1칸 기준 철거입니다."],
    },
    {
      tradeCode: "05",
      tradeNameKo: "설비공사",
      subTradeCode: "05-10",
      subTradeNameKo: "욕실 배관",
      taskNameKo: "급수·배수 배관 보수",
      defaultItemNameKo: "욕실 배관 보수",
      unit: "set",
      quantityFormula: "manual_one_set",
      costModel: {
        defaultMaterialUnitPrice: 180000,
        defaultLaborUnitPrice: 280000,
        defaultExpenseUnitPrice: 40000,
      },
      assumptions: ["배관 전체 교체가 아닌 기본 위치 보수 기준입니다."],
    },
    {
      tradeCode: "06",
      tradeNameKo: "방수공사",
      subTradeCode: "06-10",
      subTradeNameKo: "욕실 방수",
      taskNameKo: "욕실 바닥·벽체 하부 방수",
      defaultItemNameKo: "욕실 방수",
      unit: "set",
      quantityFormula: "manual_one_set",
      costModel: {
        defaultMaterialUnitPrice: 90000,
        defaultLaborUnitPrice: 180000,
        defaultExpenseUnitPrice: 20000,
      },
      assumptions: ["담수 테스트 포함 여부는 현장 정책에 따라 조정합니다."],
    },
    {
      tradeCode: "07",
      tradeNameKo: "타일공사",
      subTradeCode: "07-10",
      subTradeNameKo: "욕실 타일",
      taskNameKo: "욕실 바닥·벽 타일 시공",
      defaultItemNameKo: "욕실 타일",
      unit: "set",
      quantityFormula: "manual_one_set",
      costModel: {
        defaultMaterialUnitPrice: 650000,
        defaultLaborUnitPrice: 850000,
        defaultExpenseUnitPrice: 80000,
      },
      assumptions: ["욕실 표준 면적 기준 타일 패키지입니다."],
    },
    {
      tradeCode: "13",
      tradeNameKo: "욕실공사",
      subTradeCode: "13-01",
      subTradeNameKo: "도기·수전",
      taskNameKo: "양변기·세면기·수전 설치",
      defaultItemNameKo: "욕실 도기·수전",
      unit: "set",
      quantityFormula: "manual_one_set",
      costModel: {
        defaultMaterialUnitPrice: 780000,
        defaultLaborUnitPrice: 280000,
        defaultExpenseUnitPrice: 30000,
      },
      assumptions: ["표준형 도기와 수전 기준입니다."],
    },
    {
      tradeCode: "13",
      tradeNameKo: "욕실공사",
      subTradeCode: "13-02",
      subTradeNameKo: "천장·환풍기",
      taskNameKo: "욕실 천장재 및 환풍기 설치",
      defaultItemNameKo: "SMC 천장·환풍기",
      unit: "set",
      quantityFormula: "manual_one_set",
      costModel: {
        defaultMaterialUnitPrice: 180000,
        defaultLaborUnitPrice: 220000,
        defaultExpenseUnitPrice: 20000,
      },
      assumptions: ["돔천장 또는 SMC 천장 기본 기준입니다."],
    },
  ],
};

/**
 * 5. 주방 패키지 — P12-4: set 1 고정 단일 라인 → 12개 세부 라인으로 분해.
 *
 * 가이드: inpick-estimate-v2-product-price-pdf-fix-plan-20260513.md §7-3
 * 8,900,000 set 1 고정값은 폐기. m/ea/m² 단위로 정밀 산출.
 *
 * 주방 카운터 길이 추정 (kitchen-plan-builder.ts):
 *   <5㎡: 2.4m / 5-8㎡: 3.0m / 8-12㎡: 3.6m / ≥12㎡: 4.2m
 * 도면 치수가 있으면 그것을 우선.
 */
export const KITCHEN_STANDARD_RULE: WorkPackageRule = {
  id: "kitchen_detailed_remodel",
  match: {
    roomTypes: ["kitchen"],
    surfaceTypes: ["counter", "cabinet", "sink", "wall", "lighting"],
    materialCategories: [
      "kitchen_standard",
      "kitchen_cabinet",
      "sink_cabinet",
      "주방",
      "싱크대",
    ],
    actions: ["replace", "demolish_and_new", "new_install"],
  },
  outputLines: [
    // 02-20 철거
    {
      tradeCode: "02",
      tradeNameKo: "철거공사",
      subTradeCode: "02-20",
      subTradeNameKo: "주방 철거",
      taskNameKo: "기존 싱크대 및 주방 가구 철거",
      defaultItemNameKo: "주방 싱크대 철거",
      unit: "m",
      quantityFormula: "room_perimeter",
      quantityMultiplier: 0.5, // 주방 둘레의 절반 (싱크대 라인) 근사
      costModel: { defaultLaborUnitPrice: 45000, defaultExpenseUnitPrice: 8000 },
      assumptions: ["주방 둘레의 약 50%를 싱크대 라인으로 가정 (실측 시 조정)"],
    },
    // 05-21 급배수
    {
      tradeCode: "05",
      tradeNameKo: "설비공사",
      subTradeCode: "05-21",
      subTradeNameKo: "주방 급배수",
      taskNameKo: "주방 급수·배수 연결",
      defaultItemNameKo: "급배수 배관 연결",
      unit: "set",
      quantityFormula: "manual_one_set",
      costModel: {
        defaultMaterialUnitPrice: 80000,
        defaultLaborUnitPrice: 160000,
        defaultExpenseUnitPrice: 20000,
      },
      assumptions: ["기존 배관 위치 유지 가정. 위치 이동 시 별도 추가."],
    },
    // 04-21 전기
    {
      tradeCode: "04",
      tradeNameKo: "전기공사",
      subTradeCode: "04-21",
      subTradeNameKo: "주방 전기",
      taskNameKo: "주방 콘센트 및 전용회로",
      defaultItemNameKo: "콘센트 + 전용회로",
      unit: "set",
      quantityFormula: "manual_one_set",
      costModel: {
        defaultMaterialUnitPrice: 120000,
        defaultLaborUnitPrice: 220000,
        defaultExpenseUnitPrice: 30000,
      },
      assumptions: ["인덕션/식기세척기 전용회로 1식 가정"],
    },
    // 12-11 하부장 — 길이당 (m)
    {
      tradeCode: "12",
      tradeNameKo: "가구·싱크공사",
      subTradeCode: "12-11",
      subTradeNameKo: "하부장",
      taskNameKo: "주방 하부장 설치",
      defaultItemNameKo: "하부장 (도어+서랍 포함)",
      defaultSpec: "H850 × D600",
      unit: "m",
      quantityFormula: "room_perimeter",
      quantityMultiplier: 0.5,
      costModel: {
        materialUnitPriceKey: "selected_material_unit_price",
        defaultMaterialUnitPrice: 450000, // m당
        defaultLaborUnitPrice: 80000,
        defaultExpenseUnitPrice: 10000,
      },
      assumptions: ["m당 단가 기준. 도면 정확 시 m수 조정."],
    },
    // 12-12 상부장 — 길이당 (m)
    {
      tradeCode: "12",
      tradeNameKo: "가구·싱크공사",
      subTradeCode: "12-12",
      subTradeNameKo: "상부장",
      taskNameKo: "주방 상부장 설치",
      defaultItemNameKo: "상부장",
      defaultSpec: "H720 × D350",
      unit: "m",
      quantityFormula: "room_perimeter",
      quantityMultiplier: 0.4, // 상부장은 하부장보다 약간 짧음 (창문 영역 차감)
      costModel: {
        materialUnitPriceKey: "selected_material_unit_price",
        defaultMaterialUnitPrice: 380000,
        defaultLaborUnitPrice: 65000,
        defaultExpenseUnitPrice: 10000,
      },
      assumptions: ["창문/후드 영역 차감 후 약 40% 적용. m당 단가."],
    },
    // 12-13 키큰장 — 1ea (옵션)
    {
      tradeCode: "12",
      tradeNameKo: "가구·싱크공사",
      subTradeCode: "12-13",
      subTradeNameKo: "키큰장",
      taskNameKo: "키큰장/팬트리 설치",
      defaultItemNameKo: "키큰장 (냉장고장 또는 팬트리)",
      defaultSpec: "H2100 × W600",
      unit: "ea",
      quantityFormula: "fixture_count",
      quantityMultiplier: 1, // 기본 1ea — KitchenPlan에서 조정
      costModel: {
        materialUnitPriceKey: "selected_material_unit_price",
        defaultMaterialUnitPrice: 550000,
        defaultLaborUnitPrice: 80000,
        defaultExpenseUnitPrice: 15000,
      },
      assumptions: ["키큰장 1개 가정. 없으면 사용자가 제외 가능."],
    },
    // 12-14 상판 — 길이당 (m)
    {
      tradeCode: "12",
      tradeNameKo: "가구·싱크공사",
      subTradeCode: "12-14",
      subTradeNameKo: "상판",
      taskNameKo: "주방 상판 시공",
      defaultItemNameKo: "엔지니어드스톤 상판",
      defaultSpec: "20T",
      unit: "m",
      quantityFormula: "room_perimeter",
      quantityMultiplier: 0.5,
      costModel: {
        materialUnitPriceKey: "selected_material_unit_price",
        defaultMaterialUnitPrice: 280000,
        defaultLaborUnitPrice: 50000,
        defaultExpenseUnitPrice: 8000,
      },
      assumptions: ["엔지니어드스톤 표준. 천연석/세라믹 선택 시 단가 변동."],
    },
    // 12-15 싱크볼 — 1ea
    {
      tradeCode: "12",
      tradeNameKo: "가구·싱크공사",
      subTradeCode: "12-15",
      subTradeNameKo: "싱크볼",
      taskNameKo: "싱크볼 설치",
      defaultItemNameKo: "언더마운트 싱크볼",
      defaultSpec: "단조 SUS304",
      unit: "ea",
      quantityFormula: "fixture_count",
      quantityMultiplier: 1,
      costModel: {
        materialUnitPriceKey: "selected_material_unit_price",
        defaultMaterialUnitPrice: 220000,
        defaultLaborUnitPrice: 35000,
        defaultExpenseUnitPrice: 5000,
      },
      assumptions: ["단조 SUS304 표준. 더블볼/세라믹 선택 시 단가 변동."],
    },
    // 12-16 수전 — 1ea
    {
      tradeCode: "12",
      tradeNameKo: "가구·싱크공사",
      subTradeCode: "12-16",
      subTradeNameKo: "수전",
      taskNameKo: "주방 수전 설치",
      defaultItemNameKo: "주방 수전",
      defaultSpec: "거위목 수전",
      unit: "ea",
      quantityFormula: "fixture_count",
      quantityMultiplier: 1,
      costModel: {
        materialUnitPriceKey: "selected_material_unit_price",
        defaultMaterialUnitPrice: 120000,
        defaultLaborUnitPrice: 25000,
        defaultExpenseUnitPrice: 3000,
      },
      assumptions: ["표준 거위목 수전. 정수기 직결형 선택 시 추가."],
    },
    // 12-17 후드/쿡탑 — 1ea
    {
      tradeCode: "12",
      tradeNameKo: "가구·싱크공사",
      subTradeCode: "12-17",
      subTradeNameKo: "후드·쿡탑",
      taskNameKo: "후드·쿡탑 설치",
      defaultItemNameKo: "주방 후드 + 인덕션",
      defaultSpec: "후드 600/인덕션 3구",
      unit: "ea",
      quantityFormula: "fixture_count",
      quantityMultiplier: 1,
      costModel: {
        materialUnitPriceKey: "selected_material_unit_price",
        defaultMaterialUnitPrice: 850000, // 후드+쿡탑 묶음
        defaultLaborUnitPrice: 80000,
        defaultExpenseUnitPrice: 10000,
      },
      assumptions: ["후드 + 인덕션 패키지. 빌트인 가스/오븐 선택 시 단가 변동."],
    },
    // 07-31 백스플래시 타일 — m²
    {
      tradeCode: "07",
      tradeNameKo: "타일공사",
      subTradeCode: "07-31",
      subTradeNameKo: "주방 백스플래시",
      taskNameKo: "주방 백스플래시 타일",
      defaultItemNameKo: "포세린 타일 (백스플래시)",
      defaultSpec: "200×100 또는 300×600",
      unit: "m2",
      quantityFormula: "room_perimeter",
      // m² = 둘레의 절반 (상하부장 사이 벽) × 0.6m (높이)
      quantityMultiplier: 0.3,
      wasteFactor: 0.07,
      costModel: {
        materialUnitPriceKey: "selected_material_unit_price",
        defaultMaterialUnitPrice: 42000,
        defaultLaborUnitPrice: 38000,
        defaultExpenseUnitPrice: 4000,
      },
      assumptions: ["상하부장 사이 백스플래시. 높이 600mm 기준."],
    },
    // 15-21 폐기물
    {
      tradeCode: "15",
      tradeNameKo: "폐기물·운반·양중",
      subTradeCode: "15-21",
      subTradeNameKo: "주방 폐기물",
      taskNameKo: "주방 폐기물 반출",
      defaultItemNameKo: "폐가구·폐자재 반출",
      unit: "lot",
      quantityFormula: "manual_one_set",
      costModel: {
        defaultMaterialUnitPrice: 0,
        defaultLaborUnitPrice: 80000,
        defaultExpenseUnitPrice: 70000,
      },
      assumptions: ["1식 기준 — 양중 포함."],
    },
  ],
};

/** 6. 장판/데코타일 — 5 lines (강마루보다 저가 자재 옵션) */
export const VINYL_FLOOR_RULE: WorkPackageRule = {
  id: "floor_vinyl_sheet_replace",
  match: {
    surfaceTypes: ["floor"],
    materialCategories: [
      "vinyl_sheet",
      "lvt",
      "deco_tile",
      "장판",
      "데코타일",
      "비닐장판",
    ],
    actions: ["replace", "demolish_and_new", "new_install"],
  },
  outputLines: [
    {
      tradeCode: "02",
      tradeNameKo: "철거공사",
      subTradeCode: "02-04",
      subTradeNameKo: "기존 바닥재 철거",
      taskNameKo: "기존 장판/마루 철거",
      defaultItemNameKo: "기존 바닥재 철거",
      unit: "m2",
      quantityFormula: "floor_area",
      costModel: { defaultLaborUnitPrice: 8000, defaultExpenseUnitPrice: 1000 },
      assumptions: ["기존 바닥재 철거 가정"],
    },
    {
      tradeCode: "10",
      tradeNameKo: "바닥재공사",
      subTradeCode: "10-05",
      subTradeNameKo: "바탕 정리",
      taskNameKo: "바탕면 정리 및 평활 보수",
      defaultItemNameKo: "바탕면 정리",
      unit: "m2",
      quantityFormula: "floor_area",
      costModel: {
        defaultMaterialUnitPrice: 2500,
        defaultLaborUnitPrice: 5000,
        defaultExpenseUnitPrice: 400,
      },
      assumptions: [],
    },
    {
      tradeCode: "10",
      tradeNameKo: "바닥재공사",
      subTradeCode: "10-06",
      subTradeNameKo: "마감 시공",
      taskNameKo: "장판/데코타일 시공",
      defaultItemNameKo: "비닐장판 (LX 등)",
      defaultSpec: "2.2T 또는 LVT 3.0T",
      unit: "m2",
      quantityFormula: "floor_area",
      wasteFactor: 0.05,
      costModel: {
        materialUnitPriceKey: "selected_material_unit_price",
        defaultMaterialUnitPrice: 18000, // m²당 (강마루 65,000보다 저렴)
        defaultLaborUnitPrice: 9000,
        defaultExpenseUnitPrice: 1200,
      },
      assumptions: ["LX/콘크리트 표준 장판 기준"],
    },
    {
      tradeCode: "10",
      tradeNameKo: "바닥재공사",
      subTradeCode: "10-07",
      subTradeNameKo: "걸레받이",
      taskNameKo: "걸레받이 시공",
      defaultItemNameKo: "PVC 걸레받이",
      defaultSpec: "60mm",
      unit: "m",
      quantityFormula: "room_perimeter",
      wasteFactor: 0.05,
      costModel: {
        defaultMaterialUnitPrice: 3500,
        defaultLaborUnitPrice: 4500,
        defaultExpenseUnitPrice: 400,
      },
      assumptions: [],
    },
    {
      tradeCode: "15",
      tradeNameKo: "폐기물·운반·양중",
      subTradeCode: "15-02",
      subTradeNameKo: "폐기물 반출",
      taskNameKo: "장판 폐기물 반출",
      defaultItemNameKo: "폐기물 반출",
      unit: "lot",
      quantityFormula: "waste_volume_estimate",
      costModel: {
        defaultLaborUnitPrice: 30000,
        defaultExpenseUnitPrice: 50000,
      },
      assumptions: [],
    },
  ],
};

/** 7. 도장 — 4 lines (벽/천장 도장 마감) */
export const PAINT_RULE: WorkPackageRule = {
  id: "paint_replace",
  match: {
    surfaceTypes: ["wall", "ceiling"],
    materialCategories: ["paint", "wall_paint", "ceiling_paint", "도장", "페인트"],
    actions: ["replace", "new_install"],
  },
  outputLines: [
    {
      tradeCode: "01",
      tradeNameKo: "가설·보양공사",
      subTradeCode: "01-01",
      subTradeNameKo: "보양",
      taskNameKo: "도장 시공 전 보양",
      defaultItemNameKo: "비닐/마스킹 테이프 보양",
      unit: "m2",
      quantityFormula: "surface_area",
      costModel: {
        defaultMaterialUnitPrice: 800,
        defaultLaborUnitPrice: 1500,
        defaultExpenseUnitPrice: 100,
      },
      assumptions: ["바닥/창호/콘센트 보양"],
    },
    {
      tradeCode: "08",
      tradeNameKo: "도장공사",
      subTradeCode: "08-01",
      subTradeNameKo: "바탕 정리",
      taskNameKo: "바탕면 보수 및 면정리",
      defaultItemNameKo: "퍼티·샌딩",
      unit: "m2",
      quantityFormula: "surface_area",
      costModel: {
        defaultMaterialUnitPrice: 1500,
        defaultLaborUnitPrice: 3000,
        defaultExpenseUnitPrice: 200,
      },
      assumptions: ["크랙/못자국 보수 포함"],
    },
    {
      tradeCode: "08",
      tradeNameKo: "도장공사",
      subTradeCode: "08-02",
      subTradeNameKo: "프라이머",
      taskNameKo: "프라이머 시공",
      defaultItemNameKo: "수성 프라이머",
      unit: "m2",
      quantityFormula: "surface_area",
      wasteFactor: 0.03,
      costModel: {
        defaultMaterialUnitPrice: 1800,
        defaultLaborUnitPrice: 2500,
        defaultExpenseUnitPrice: 200,
      },
      assumptions: [],
    },
    {
      tradeCode: "08",
      tradeNameKo: "도장공사",
      subTradeCode: "08-03",
      subTradeNameKo: "마감 도장 (2회)",
      taskNameKo: "친환경 수성 도장 2회",
      defaultItemNameKo: "친환경 수성 페인트",
      defaultSpec: "VOC-free",
      unit: "m2",
      quantityFormula: "surface_area",
      wasteFactor: 0.05,
      costModel: {
        materialUnitPriceKey: "selected_material_unit_price",
        defaultMaterialUnitPrice: 4500, // m²당 (2회 시공 기준)
        defaultLaborUnitPrice: 6000,
        defaultExpenseUnitPrice: 500,
      },
      assumptions: ["프리미엄 친환경 페인트 2회 시공 기준"],
    },
  ],
};

/** 8. 조명·전기 기본 (방별) — 4 lines */
export const LIGHTING_ELECTRICAL_RULE: WorkPackageRule = {
  id: "lighting_basic_replace",
  match: {
    surfaceTypes: ["lighting", "ceiling"],
    materialCategories: [
      "lighting",
      "led_recessed",
      "pendant_light",
      "조명",
      "LED",
      "다운라이트",
      "펜던트",
    ],
    actions: ["replace", "new_install"],
  },
  outputLines: [
    {
      tradeCode: "02",
      tradeNameKo: "철거공사",
      subTradeCode: "02-05",
      subTradeNameKo: "조명 철거",
      taskNameKo: "기존 조명 철거",
      defaultItemNameKo: "기존 조명기구 철거",
      unit: "ea",
      quantityFormula: "fixture_count",
      quantityMultiplier: 1,
      costModel: { defaultLaborUnitPrice: 15000, defaultExpenseUnitPrice: 2000 },
      assumptions: ["방당 평균 1ea 가정"],
    },
    {
      tradeCode: "04",
      tradeNameKo: "전기공사",
      subTradeCode: "04-01",
      subTradeNameKo: "배선",
      taskNameKo: "조명 배선 점검·보강",
      defaultItemNameKo: "전선 + 분기",
      unit: "ea",
      quantityFormula: "fixture_count",
      quantityMultiplier: 1,
      costModel: {
        defaultMaterialUnitPrice: 12000,
        defaultLaborUnitPrice: 25000,
        defaultExpenseUnitPrice: 2000,
      },
      assumptions: [],
    },
    {
      tradeCode: "04",
      tradeNameKo: "전기공사",
      subTradeCode: "04-02",
      subTradeNameKo: "조명기구 설치",
      taskNameKo: "조명기구 설치",
      defaultItemNameKo: "LED 매입등 또는 펜던트",
      defaultSpec: "150mm 매입 / 12W LED",
      unit: "ea",
      quantityFormula: "fixture_count",
      quantityMultiplier: 1,
      costModel: {
        materialUnitPriceKey: "selected_material_unit_price",
        defaultMaterialUnitPrice: 45000,
        defaultLaborUnitPrice: 22000,
        defaultExpenseUnitPrice: 3000,
      },
      assumptions: ["방 1개당 평균 1개 (LED 매입등 기본)"],
    },
    {
      tradeCode: "04",
      tradeNameKo: "전기공사",
      subTradeCode: "04-03",
      subTradeNameKo: "스위치·콘센트",
      taskNameKo: "스위치 및 콘센트 교체",
      defaultItemNameKo: "표준 스위치/콘센트",
      unit: "ea",
      quantityFormula: "fixture_count",
      quantityMultiplier: 2,
      costModel: {
        defaultMaterialUnitPrice: 8000,
        defaultLaborUnitPrice: 12000,
        defaultExpenseUnitPrice: 1000,
      },
      assumptions: ["방당 평균 스위치 1 + 콘센트 1 (총 2ea)"],
    },
  ],
};

/** 9. 가설·보양·청소 (전체 프로젝트 1식) — 3 lines */
export const SCAFFOLD_PROTECTION_RULE: WorkPackageRule = {
  id: "scaffold_protection_lump",
  match: {
    // 전체 프로젝트에 항상 적용 — surface 무관, project 단위 추가
    surfaceTypes: ["floor", "wall", "ceiling"], // dummy match — 1방 이상 있으면 1회 추가
    materialCategories: [
      "scaffold_protection",
      "보양",
      "가설",
      "준공청소",
      "construction_cleaning",
    ],
    actions: ["new_install", "replace", "demolish_and_new"],
  },
  outputLines: [
    {
      tradeCode: "01",
      tradeNameKo: "가설·보양공사",
      subTradeCode: "01-10",
      subTradeNameKo: "현장 보양 (전체)",
      taskNameKo: "현장 전반 보양",
      defaultItemNameKo: "바닥/엘리베이터/계단 보양",
      unit: "lot",
      quantityFormula: "manual_one_set",
      costModel: {
        defaultMaterialUnitPrice: 150000,
        defaultLaborUnitPrice: 200000,
        defaultExpenseUnitPrice: 30000,
      },
      assumptions: ["프로젝트 1식 기준"],
    },
    {
      tradeCode: "16",
      tradeNameKo: "준공청소",
      subTradeCode: "16-01",
      subTradeNameKo: "입주청소",
      taskNameKo: "준공·입주청소",
      defaultItemNameKo: "전면 청소 + 유리/욕실 디테일",
      unit: "lot",
      quantityFormula: "manual_one_set",
      costModel: {
        defaultMaterialUnitPrice: 80000,
        defaultLaborUnitPrice: 220000,
        defaultExpenseUnitPrice: 20000,
      },
      assumptions: ["전체 평수 기준 1식. 30평 기준 — 평수 30평 이상은 별도 추가."],
    },
    {
      tradeCode: "15",
      tradeNameKo: "폐기물·운반·양중",
      subTradeCode: "15-99",
      subTradeNameKo: "양중·운반 (전체)",
      taskNameKo: "프로젝트 양중·운반 일괄",
      defaultItemNameKo: "엘리베이터 양중 + 차량 운반",
      unit: "lot",
      quantityFormula: "manual_one_set",
      costModel: {
        defaultMaterialUnitPrice: 0,
        defaultLaborUnitPrice: 180000,
        defaultExpenseUnitPrice: 120000,
      },
      assumptions: ["고층 양중료 별도. 1식 기준."],
    },
  ],
};

/** 10. 창호 — 3 lines (창호 교체 또는 추가) */
export const WINDOW_DOOR_RULE: WorkPackageRule = {
  id: "window_door_replace",
  match: {
    surfaceTypes: ["window", "door"],
    materialCategories: [
      "window",
      "door",
      "frame",
      "창호",
      "도어",
      "방화문",
      "현관문",
    ],
    actions: ["replace", "new_install"],
  },
  outputLines: [
    {
      tradeCode: "02",
      tradeNameKo: "철거공사",
      subTradeCode: "02-06",
      subTradeNameKo: "창호·도어 철거",
      taskNameKo: "기존 창호/도어 철거",
      defaultItemNameKo: "창호·도어 철거",
      unit: "ea",
      quantityFormula: "fixture_count",
      quantityMultiplier: 1,
      costModel: { defaultLaborUnitPrice: 35000, defaultExpenseUnitPrice: 5000 },
      assumptions: [],
    },
    {
      tradeCode: "11",
      tradeNameKo: "창호·금속공사",
      subTradeCode: "11-01",
      subTradeNameKo: "창호·도어 설치",
      taskNameKo: "창호 또는 도어 설치",
      defaultItemNameKo: "방문 또는 시스템 창호",
      defaultSpec: "ABS 도어 / 22T 알루미늄",
      unit: "ea",
      quantityFormula: "fixture_count",
      quantityMultiplier: 1,
      costModel: {
        materialUnitPriceKey: "selected_material_unit_price",
        defaultMaterialUnitPrice: 380000, // 도어 표준
        defaultLaborUnitPrice: 80000,
        defaultExpenseUnitPrice: 10000,
      },
      assumptions: ["방문 ABS 도어 기준. 현관문/시스템창호는 단가 변동."],
    },
    {
      tradeCode: "11",
      tradeNameKo: "창호·금속공사",
      subTradeCode: "11-02",
      subTradeNameKo: "마감·실리콘",
      taskNameKo: "창호 주변 마감 및 실리콘",
      defaultItemNameKo: "마감재 + 실리콘",
      unit: "ea",
      quantityFormula: "fixture_count",
      quantityMultiplier: 1,
      costModel: {
        defaultMaterialUnitPrice: 15000,
        defaultLaborUnitPrice: 25000,
        defaultExpenseUnitPrice: 2000,
      },
      assumptions: [],
    },
  ],
};

/** 모든 규칙 — 견적 엔진이 surfacePlan과 매칭할 때 순회 */
export const ALL_WORK_PACKAGE_RULES: WorkPackageRule[] = [
  WOOD_FLOOR_RULE,
  WALLPAPER_RULE,
  PORCELAIN_TILE_RULE,
  BATHROOM_FULL_REMODEL_RULE,
  KITCHEN_STANDARD_RULE,
  // P13-3 추가:
  VINYL_FLOOR_RULE,
  PAINT_RULE,
  LIGHTING_ELECTRICAL_RULE,
  SCAFFOLD_PROTECTION_RULE,
  WINDOW_DOOR_RULE,
];
